{
 "title": "GLAuth",
 "tags": [
  "prometheus",
  "glauth"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total bind requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glauth_proxy_frontend{metric=\"bind_reqs\"}[$__range]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Bind requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(glauth_proxy_frontend{metric=\"bind_reqs\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Bind failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sum(glauth_proxy_frontend{metric=\"bind_failures\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Total search requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glauth_proxy_frontend{metric=\"search_reqs\"}[$__range]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Search requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "sum(glauth_proxy_frontend{metric=\"search_reqs\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Search successes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(glauth_proxy_frontend{metric=\"search_successes\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Search failures",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "sum(glauth_proxy_frontend{metric=\"search_failures\"})",
     "legendFormat": "count"
    }
   ]
  }
 ]
}